INSERT INTO notes (name, content, folderId)
VALUES ('NOTE A', 'THIS IS THE CONTENT OF NOTE A', 1),
 ('NOTE A', 'THIS IS THE CONTENT OF NOTE B', 2),
 ('NOTE A', 'THIS IS THE CONTENT OF NOTE C', 3),
 ('NOTE A', 'THIS IS THE CONTENT OF NOTE D', 4); 